// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-qcK9UEPpTzzMG5M4Znp_aFspzq1RJ_M',
    appId: '1:624601549184:web:e9933c2adef27709ba9965',
    messagingSenderId: '624601549184',
    projectId: 'smart-18',
    authDomain: 'smart-18.firebaseapp.com',
    storageBucket: 'smart-18.firebasestorage.app',
    measurementId: 'G-NHHTF7GDZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrC4T29BjI3WVAKGjPCkoyfDcczdAeMeQ',
    appId: '1:624601549184:android:6705e93e51378903ba9965',
    messagingSenderId: '624601549184',
    projectId: 'smart-18',
    storageBucket: 'smart-18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3gYoTn4SAsrbRN1nBPfAoNV2tDRkijLk',
    appId: '1:624601549184:ios:f13da5ddce6c6a7dba9965',
    messagingSenderId: '624601549184',
    projectId: 'smart-18',
    storageBucket: 'smart-18.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3gYoTn4SAsrbRN1nBPfAoNV2tDRkijLk',
    appId: '1:624601549184:ios:f13da5ddce6c6a7dba9965',
    messagingSenderId: '624601549184',
    projectId: 'smart-18',
    storageBucket: 'smart-18.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-qcK9UEPpTzzMG5M4Znp_aFspzq1RJ_M',
    appId: '1:624601549184:web:e02a9fd481a741c0ba9965',
    messagingSenderId: '624601549184',
    projectId: 'smart-18',
    authDomain: 'smart-18.firebaseapp.com',
    storageBucket: 'smart-18.firebasestorage.app',
    measurementId: 'G-93M6HPEY72',
  );
}
